vault_addr: "{{ lookup('env', 'VAULT_ADDR') | default('http://127.0.0.1:8200', true) }}"
vault_role_id: "{{ lookup('env', 'VAULT_ROLE_ID') | default('', true) }}"
vault_secret_id: "{{ lookup('env', 'VAULT_SECRET_ID') | default('', true) }}"
